---
- name: check if fzf is installed
  stat:
    path: "{{ fzf_bin_path }}"
  register: fzf_installed

- name: Fetch the latest version of the code
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1
  when: fzf_installed.stat.exists == false
  changed_when: false

- name: Install fzf
  shell: "~/.fzf/install --no-key-bindings --no-completion --no-update-rc"
  args:
    executable: /bin/bash
  when: fzf_installed.stat.exists == false
  changed_when: false

- name: Copy fzf binary to "{{ fzf_bin_path }}"
  copy:
    src: "~/.fzf/bin/fzf"
    dest: "{{ fzf_bin_path }}"
    mode: 0744
  when: fzf_installed.stat.exists == false
  changed_when: false
